### ISSUE TITLE
Confusion about the implementation.

### ISSUE THREAD

**Issue by HaiyongJiang** [Regenerator/kdnets#2]
Dear @Regenerator , Thank you for open-sourcing your implementation of kd-net. I have some questions about the implementation.
I read the implementation of segmentation on point clouds. I found it is inconsistent as Eq.1 in the paper. In the paper, the features for non-leaf nodes are computed by selecting a convolutional result of the splitting dimension. But in your implementation, these features are computed by average the convolutional results of all dimensions. 
Is there anything that I misunderstood it? Thank you for helping me out.

**Comment by Regenerator** [comment]
Hi @HaiyongJiang,

The non-leaf nodes are actually computed not by taking a mean but by taking a sum of convolutional results, weighted by coefficients. For kd-trees used in this code, these coefficients are simply one-hot encoded vectors of splitting dimensions, which makes all the weights equal to zero except a single coefficient, corresponding to the splitting direction in the current node.

I hope this will clear out the misunderstanding.

**Comment by HaiyongJiang** [comment]
Thank you. You did help me out.
